// Provides accessors to an embedded ROM if the header generated by tools/bin2c.py
// is present at `Oxygen/sonic3air/___internal/rom_data.h`.

#if __has_include("___internal/rom_data.h")
#include "___internal/rom_data.h"
extern "C" const unsigned char* get_embedded_rom()
{
    return game_bin_data;
}

extern "C" unsigned int get_embedded_rom_size()
{
    return game_bin_data_size;
}
#else
extern "C" const unsigned char* get_embedded_rom()
{
    return nullptr;
}

extern "C" unsigned int get_embedded_rom_size()
{
    return 0;
}
#endif
